### PR TITLE
Artifactory Hosting

### PR DESCRIPTION
**Pull request by JoshuaRogan**
### Description
* Ability to publish to artifactory
    * builds the directories before publishing
* Removes all dist files (and git ignore them)
* File structure now has a `dist` directory containing the build files

### Artifactory Setup
This setup will work for both `yarn` and `npm`. If you run into issues consult [Artifactory NPM Docs](https://www.jfrog.com/confluence/display/RTF/Npm+Registry) first

1. Verify you can login to [Artifactory Wikia](https://artifactory.wikia-inc.com/artifactory/webapp/#/home)
2. Change wikia scoped packages to use artifactory `npm config set @wikia:registry https://artifactory.wikia-inc.com/artifactory/api/npm/npm-source/`
3. Run `npm login --scope=@wikia` 
    * Use artifactory login and artifactory API key for password by going to "Edit Profile" in artifactory web ui

### TODO
- [ ] Bump version (determine if this should be a major version)
- [x] Setup "publish" npm
- [x] Update readme to change the registry to artifactory

@vforge

### CODE REVIEW

**Comment by vforge** [comment]
Let's divide the artifactory work into two PRs (releases):

1) Add push to artifactory
- `yarn release*` should push the image to artifactory (assuming that the config) at the end

(this will effectively mean that on this versioj both artifactory and github links can be used in `package.json`)

2) Tweak build process (this can be multiple PR, but only one release would be needed)
- `yarn build` should only build the styleguide to `docs/`
- There will be a new entry in the `.gitignore` for the `dist/`
- the new command (eg. `yarn build:lib`) will build library files to `dist/` using the current process (instead of putting them in `/`.
- The `source/` directory contents are moved to the `/`.
- After package has been built to `dist/` it will be zipped (all this can be done by npm) and it's going to be published to both github releases and artifactory using process from (1)

**Comment by JoshuaRogan** [comment]
I think I am able to do everything in this pr. Version 2.0 is deployed to [artifactory](https://artifactory.wikia-inc.com/artifactory/webapp/#/artifacts/browse/simple/General/wikia-npm/@wikia/react-common/-/@wikia/react-common-2.0.0.tgz) with no changes. 

Updates:
* removed source directory and created `/dist` directory for all generated files (except styleguide doc with lives in `docs` still
* `yarn release*` will run yarn `publish` which pushes to artifactory 


I _think_ I accurately did what you were suggesting but I did not do it in two releases because we already have a release on artifactory

**Comment by JoshuaRogan** [comment]
Unsure why travis is failling:
```
SLint: 5.9.0.
ESLint couldn't find the plugin "eslint-plugin-ie11". This can happen for a couple different reasons:
1. If ESLint is installed globally, then make sure eslint-plugin-ie11 is also installed globally. A globally-installed ESLint cannot find a locally-installed plugin.
2. If ESLint is installed locally, then it's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm i eslint-plugin-ie11@latest --save-dev
Path to ESLint package: /home/travis/build/Wikia/react-common/node_modules/eslint
```

**Comment by vforge** [comment]
I'm going to resolve conflicts just prior to merge, dw.

**Pull request merged**
