### PR TITLE
add iconName to Dropdown

### PR DESCRIPTION
**Pull request by jsutterfield**
This PR updates the Dropdown component to take an optional `iconName` which is used to determine the chevron for the dropdown.

We're using this Dropdown for the category picker in Feeds. The designs call for a different chevron for desktop vs mobile. See:
https://app.zeplin.io/project/5b563d14e825ad811a6d3226/screen/5c6260e5ad81ec99d9f194b1
https://app.zeplin.io/project/5b563d14e825ad811a6d3226/screen/5c6260e9959ef19a21f6ae39

/cc @Wikia/iwing @vforge 

Relates to https://github.com/Wikia/fepo/pull/439

### CODE REVIEW

**Comment by vforge** [comment]
@jsutterfield Since the `<Icon>` is deprecated and will be removed in the near (as it requires the Sprite anyway) can we specify the component instead?
```js
<Dropdown toggle="Toggle dropdown" icon=IconDropdownTiny >
    <p style={{padding: '12px'}}>I am a text inside dropdown!</p>
</Dropdown>
```

**Comment by vforge** [comment]
Sorry for not catching that earlier - the icon should already be replaced in https://github.com/Wikia/react-design-system/pull/89 ages ago

**Comment by jsutterfield** [comment]
@vforge I ran into the following error when trying to pass the icon-specific component as a parameter:

screen shot 2019-02-21 at 2 09 44 pm
screen shot 2019-02-21 at 2 14 08 pm

I opted to take the same approach that [BannerNotification](https://github.com/Wikia/react-common/blob/master/source/components/BannerNotification/index.js) does. Namely, using strings as the arguments and proptypes but using the value of the string to figure out which icon component to render.

**Comment by vforge** [comment]
https://github.com/Wikia/react-common/releases/tag/3.3.0

**Pull request merged**
